classes: {
  exception: {
    style: {
      stroke: red
      font-color: red
    }
  }
  parser
  ext: {
    style: {
      stroke: green
    }
  }
  cache: {
    style: {
      stroke: green
      font-color: black
    }
  }
  transparent: {
    style: {
      stroke: transparent
    }
  }
  step: {
    style: {
      stroke: magenta
    }
  }
  definition: {
    style: {
      font-color: black
    }
  }
}
bin: Расшифровка BIN сообщений (BIN worker) {
  shape: sequence_diagram

  parser: Парсер {class: parser}
  store: Хранилище {class: ext}
  ecma: ECMA {class: ext}
  log: Журнал {class: ext}
  Главный цикл (продолжать пока есть BIN для расшифровки): {
    Обработка одного BIN: {
      parser <- store
      Сформировать списки тиков: {
        parser -> parser: |md
          - списки тиков для первой и второй педали
          - список тиков для меток
          - сообщения о неработающих педалях, пропусках тиков, дребезге и дублировании меток
        | {class: definition}
      }
      Рассчитать направление: {
        parser -> parser: |md
          - сообщение -невозможно определить направление, завершение обработки BIN
        | {class: definition}
      }
      Рассчитать мгновенные скорости: {
        parser <- store: Получить поправочные коэффициенты для считывателей {class: cache}
        parser -> parser: |md
          - расчет скоростей с учетом поправочных коэффициентов по направлениям
          - сгладить выбросы
          - сообщения о превышении допустимых скоростей и возможной потери качества
        | {class: definition}
      }
      Рассчитать межосевые расстояния и положения меток: {
        parser -> parser: |md
          - расчет межосевых состояний состава по скоростям
          - расчет положения и "длины" меток
          - сообщения о ошибках при определении межосевых расстояний и положений меток
        | {class: definition}
      }
      Сопоставить межосевые расстояния и положения меток группам подвижного состава: {
        parser <- store: Получит межосевые расстояния по группам {class: cache}
        parser -> parser: |md
          - сопоставить межосевые расстояния и межосевые для групп единиц подвижного состава
          - сформировать состав сопоставив выделенную единицу подвижного состава группе
          - улучшить сопоставление эвристическими методами
          - сообщения об ошибках сопоставления
        | {class: definition}
      }
      Уточнить состав по инвентарным номерам: {
        parser <- store: Получить данные по инвентарным номерам подвижного состава {class: cache}
        parser -> parser: |md
          - "прикрепить" метки к единице подвижного состава
          - сопоставить данные полученные по инвентарным номера с единицей подвижного состава
          - сообщения о ошибках при сопоставлении данных по инвентарным номерам
        | {class: definition}
      }
      Сформировать сообщения ЕСМА: {
        parser -> ecma: |md
          - сопоставить список ошибок со списком ошибок, которые необходимо отобразить в ЕСМА
          - отослать в ЕСМА ошибки при разборе BIN
          - отослать в ЕСМА сообщения о нормальном работе для возможных ошибок
        | {class: definition}
      }
      Пересчитать поправочные коэффициенты: {
        parser -> store: |md
          - проверить качество разбора BIN и возможность пересчета
          - по данным о межосевых расстояниях конкретного локомотива и данным из BIN произвести пересчет
        | {class: cache}
      }
      parser -> store: |md
        - сохранить данные о промежуточных результатах расчета
        - сохранить сообщения об ошибках
        - если возможно сформировать и сохранить 2033
      | {class: definition}
      parser -> log: |md
        - перехватить исключение
        - записать в системный журнал
        - исключение не приводит к завершению цикла
        - BIN при обработке которого произошла ошибка больше не обрабатывается
      | {class: exception}
    }
  }
}
