@startuml
title Расшифровка BIN сообщений (BIN worker)
  participant  Парсер as parser  #9999ff
  participant  Хранилище as store #99ff99
  participant  ECMA as ecma  #99ff99
  participant  Журнал as log #FF9999
  loop Главный цикл (продолжать пока есть BIN для расшифровки)
    alt Обработка одного BIN
        parser <[#blue]- store: Получить исходные данные
        parser -> parser
        note right #efefef
        - сформировать списки тиков для первой и второй педали
        - сформировать список тиков для меток
        - сообщения о неработающих педалях, пропусках тиков, дребезге и дублировании меток
        end note

        parser -> parser
        note right  #eeeeee
        - расчет направления
        - если невозможно определить направление, завершение обработки BIN
        end note

        parser <[#blue]- store: Получить поправочные коэффициенты для считывателей 
        parser -> parser
        note right #eeeeee
          - расчет мгновенных скоростей с учетом поправочных коэффициентов по направлениям
          - сгладить выбросы
          - сообщения о превышении допустимых скоростей и возможной потери качества
        end note

        parser -> parser
        note right #eeeeee
          - расчет межосевых состояний состава по скоростям
          - расчет положения и "длины" меток
          - сообщения о ошибках при определении межосевых расстояний и положений меток
        end note

        parser <[#blue]- store: Получит межосевые расстояния по группам 
        parser -> parser
        note right #eeeeee
          - сопоставить межосевые расстояния и межосевые для групп единиц подвижного состава
          - сформировать состав сопоставив выделенную единицу подвижного состава группе
          - улучшить сопоставление эвристическими методами
          - сообщения об ошибках сопоставления
        end note

        parser <[#blue]- store: Получить данные по инвентарным номерам подвижного состава 
        parser -> parser
        note right #eeeeee
          - "прикрепить" метки к единице подвижного состава
          - сопоставить данные полученные по инвентарным номера с единицей подвижного состава
          - сообщения о ошибках при сопоставлении данных по инвентарным номерам
        end note

        parser -> parser
        note right #eeeeee
          - если нет критических ошибок сформировать 2033
        end note

        parser -[#red]> ecma : Отослать в ЕСМА сообщения об ошибках при разборе BIN
        parser -[#green]> ecma : Отослать в ЕСМА  сообщения о нормальном работе для отмены ошибок

        parser -[#blue]> store: Пересчитать поправочные коэффициенты

        parser -[#blue]> store: Сохранить данные о промежуточных результатах расчета и сообщения об ошибках

    else Исключение при обработке BIN
      parser-[#red]>log : Записать исключение в системный журнал
    end
  end
@enduml
